name: Cleanup GHCR images

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

jobs:
  cleanup:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Cleanup old images (keep last 10)
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          keep-n-tagged: 10
          delete-untagged: true
